function h = checkbox(parent, text, callback)
    h = uicontrol('Parent', parent, ...
                  'Style', 'checkbox', ...
                  'String', text, ...
                  'callback', callback);
end