function h = inputText(parent, tag, callback)
    h = uicontrol('Parent', parent, ...
                  'Tag', tag, ...
                  'Style', 'edit', ...
                  'String', '-', ...
                  'BackgroundColor','white', ...
                  'Callback', callback);
end

