function h = popupMenu(parent, text, callback)
    h = uicontrol('Parent', parent, ...
                  'Style', 'popupmenu', ...
                  'String', text, ...
                  'BackgroundColor','white', ...
                  'callback', callback);
end
